# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d6099e325d3ac55412d27296bd4ed50bbcbcedc24380e4c2dddfb6de36a2abe046be3c3e09861706133324a792fab60647d9a5ab80bf92a4e3ad1f26b9ce454

test:
  secret_key_base: e92acecebcaac745e3046240c8009dd67927989ac11cf4e09a5d1e3fa6074cbc5c73172c8f08549b3f15466728aa080ad51c7615b1b1f68828721715afed5663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
